language: objective-c
osx_image: xcode7

before_install:
  - export PROJECT=KGNGradientView
  - export SCHEME=$PROJECT
  - export LANG=en_US.UTF-8

  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script: xctool clean test -project "$PROJECT.xcodeproj" -scheme $SCHEME -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
